services:

  techradarui:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        REACT_APP_TECHNOLOGY_SITE_URL_DEV: https://technologyradar.alwaysmoveforward.com
        REACT_APP_TECHNOLOGY_API_URL_DEV: https://api.technologyradar.alwaysmoveforward.com
        REACT_APP_TECHNOLOGY_MANAGE_RADARS_URL_DEV: https://manage.technologyradar.alwaysmoveforward.com
        REACT_APP_TECHNOLOGY_ADMIN_URL_DEV: https://admin.technologyradar.alwaysmoveforward.com        
    container_name: techradarui
    ports:
      - "8082:80"
  
