export const SETRADARCOLLECTION = "SETRADARCOLLECTION";
export const SETSOURCERADARINSTANCE = "SETSOURCERADARINSTANCE";
export const SETCURRENTRADARINSTANCE = "SETCURRENTRADARINSTANCE";
export const GETSOURCERADARINSTANCE = "GETSOURCERADARINSTANCE";
export const UPDATESHOULDADDTOGGLE = "UPDATESHOULDADDTOGGLE";
export const SETRADARTYPECOLLECTION = "SETRADARTYPECOLLECTION";
export const SETSELECTEDRADARITEM = "SETSELECTEDRADARITEM";
export const SETSELECTEDRADARITEMCHANGED = "SETSELECTEDRADARITEMCHANGED";