export const SETASSOCIATEDRADARTEMPLATES = "SETASSOCIATEDRADARTEMPLATES";
export const SETRADARTEMPLATECOLLECTION = "SETRADARTEMPLATECOLLECTION";
export const SETSHAREDRADARTEMPLATECOLLECTION = "SETSHAREDRADARTYPECOLLECTION";
export const SETSELECTEDRADARTEMPLATE = "SETSELECTEDRADARTYPE";
export const SETSHOWEDIT = "SETSHOWEDIT";
export const ADDTARGETUSERTOSTATE = "ADDTARGETUSERTOSTATE";